### ISSUE TITLE
[Enhancement] 希望能够自定义学生回复时打字速度

### ISSUE THREAD

**Issue by xiaofeiTM233** [Mark9804/blue-archive-story-viewer#137]
### 功能描述

希望能够自定义学生回复时打字速度，目前的没看出是一个随机数还是一个固定值，但是比较久
如果选择跳过打字这部分or加速这部分时间，可能可以让sensei的体验更好（不是为了仿的更真）
想法：
1. 直接缩短全局时间，但这样会不注重还原
2. 点击momotalk空白区域跳过
3. 允许自定义速度
4. 2和3都要
最终看momotalk我还是要回到游戏内看的（我反正是这样），如果已经看了一遍或者还要再看一遍的话，那这部分其实是有点浪费时间的了

### 具体操作

个人目前就是直接用脚本加速了，因为学生的打字时间加起来真的很长

**Comment by mark9804** [comment]
> 目前的没看出是一个随机数还是一个固定值，

是游戏内给的值，游戏内定义了每个学生回复的“打字时间”，即下文中的 `FeedbackTimeMillisec`

```yaml
  - MessageGroupId: 100000011
    Id: 329
    CharacterId: 10000
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100000020
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ''
    MessageKR: 후훗. 고생했어.
    MessageJP: ふふっ、お疲れ様
    MessageCN: 呵呵，辛苦了
    MessageEN: Heh. Good job.
    MessageTH: ฮุฮุ ทำได้ดีมาก
    MessageTW: 呵呵，辛苦了
```

> 允许自定义速度

目前的计划是添加一个立即显示的功能开关。但是我们 UI 最近正在享受福报，给不出图，这个功能我们有意向添加，但是优先级不是非常高
