### ISSUE TITLE
momotalk 数据结构和组件结构草案

### ISSUE THREAD

**Issue by mark9804** [Mark9804/blue-archive-story-viewer#22]
此信息已过时，参考 #24 .

<details>
<summary>过时内容</summary>

# momotalk 数据结构和组件结构草案

我想了一下，本来是想解包出来之后直接用韩国人的数据结构的，但是想起来件重要的事就是他们只有日语，不用做翻译，所以还是得自己实现

### 相对于羁绊剧情入口的位置

聊天大体上可以分成羁绊剧情前和羁绊剧情后，使用 `before` 和 `after` 进行区分。

##### `before`: `Array`

放置进入羁绊剧情前的 momotalk 内容。

##### `after`: `Array`

放置完成羁绊剧情后的 momotalk 内容。

#### 示例

```yml
chats:
  before: [...chat_before]
  after: [...chat_after]
```

#### 游戏内容示例

<img src="https://raw.githubusercontent.com/Mark9804/typora-image-repo/master/uPic/image-20221022133116061.png" alt="image-20221022133116061" style="zoom:50%;" />

##### `type`: `String<chat>`

标记聊天组件的样式。纯文本信息当中，`type` 的值为 `chat`。（是否应该使用 `string` 作为值？）

##### `content`: `Object<content.zh, content.jp>`

标记聊天组件的内容。纯文本信息中，`content` 的值为 `Object`。

###### `content.zh`: `String`

简体中文聊天内容。

###### `content.ja`: `String`

日语聊天内容。

##### `sender`: `String`

标记聊天信息是由谁发出的。一般只有 `student` 和 `teacher` 两个取值。

#### 数据结构示例

```yml
chats:
  before:
    - type: chat
      content:
        zh: 一直以来承蒙照顾。
        ja: いつもお世話になっております。
      sender: student
    - type: chat
      content:
        zh: ……
        ja: ……
      sender: student
```

### 游戏内容示例

<img src="https://raw.githubusercontent.com/Mark9804/typora-image-repo/master/uPic/image-20221022133546784.png" alt="image-20221022133546784" style="zoom:50%;" />

##### `type`: `String<image>`

标记聊天组件样式为图片。

##### `url`: `String<link>`

标记图片的 url。

##### `sender`: `String`

同“普通文本信息”。

### 数据结构示例

```yml
    - type: image
      url: "~.webp"
      sender: student
```

##### 游戏内容示例

<img src="https://raw.githubusercontent.com/Mark9804/typora-image-repo/master/uPic/image-20221022133758721.png" alt="image-20221022133758721" style="zoom:50%;" />

###### `type`: `String<option>`

标记组件样式为选择肢。

###### `options`: `Array<option>`

存放选择肢内容。

`option.content`: `Object`

因为老师的回复只出现过字符串，因此应该可以认为只需要记录文字内容（中文、日语）。

`option.content.zh`: `String`

老师的回复（中文）

`option.content.ja`: `String`

老师的回复（日语）

###### `selection`: `Number`

标明这个选项会触发学生哪一段学生回复。

###### `sender`: `String`

同“普通文本信息”

##### 数据结构示例

```yml
    - type: option
      options:
        - content:
            zh: ……现在？大晚上的……？
            ja: ……今？まだ夜中なのに……？
          selection: 1
        - content:
            zh: 我在做梦……？
            ja: 夢……？
          selection: 2
      sender: teacher
```

###### `type`: `String<diversion>`

标记这是一段根据选择不同触发不同内容的类型。

##### `variations`: `Array<selections>`

存放不同触发结果。

##### `selections.selection`: `Number`

对应老师选项的 `selection` ，触发不同的内容。

###### `selection.replies`: `Array<普通聊天信息>`

见“普通文本信息”的定义。

数据结构：

```yml
    - type: diversion
      variations:
        - selection: 1
          replies:
            - type: chat
              content:
                zh: 回复（第 1 条，共 2 条）
                ja: 大丈夫、大したことじゃない
              sender: student
            - type: chat
              content:
                zh: 回复（第 2 条，共 2 条）
                ja: じゃあ、またね。先生
              sender: student
        - selection: 2
          replies: [...chats]
```

#### 游戏内容示例

<img src="https://raw.githubusercontent.com/Mark9804/typora-image-repo/master/uPic/image-20221022134346929.png" alt="image-20221022134346929" style="zoom:50%;" />

##### `type`: `String<link>`

标记这是一个 `router-link`，点击将会跳转到对应的羁绊内容。

##### `content`: `Object`

`content.zh`, `content.ja`：定义按钮显示的文字。

##### `link`: `String`

标记 `router-link to="…"` 的跳转目标。

数据结构：

```yml
    - type: link
      content:
        zh: 前往xx的羁绊剧情
        ja: xxの絆ストーリーへ
      link: 10024_story_01
```
</details>
